//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalUserAcademicInfo
    {
        public int ExternalUserAcademicInfoID { get; set; }
        public Nullable<int> ExternalUserLoginID { get; set; }
        public Nullable<int> SchoolStandardId { get; set; }
        public Nullable<int> SchoolSectionId { get; set; }
        public Nullable<int> AcademicYearId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public string LastUpdatedDate { get; set; }
        public Nullable<int> SchoolStreamID { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual ExternalUserLogin ExternalUserLogin { get; set; }
        public virtual ExternalUserLogin ExternalUserLogin1 { get; set; }
        public virtual ExternalUserLogin ExternalUserLogin2 { get; set; }
        public virtual SchoolSection SchoolSection { get; set; }
        public virtual SchoolStandard SchoolStandard { get; set; }
        public virtual SchoolStream SchoolStream { get; set; }
    }
}
