//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalUserLogin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalUserLogin()
        {
            this.ExternalUserAcademicInfoes = new HashSet<ExternalUserAcademicInfo>();
            this.ExternalUserAcademicInfoes1 = new HashSet<ExternalUserAcademicInfo>();
            this.ExternalUserAcademicInfoes2 = new HashSet<ExternalUserAcademicInfo>();
            this.ExternalUserLogin_UserGroup_Mapping = new HashSet<ExternalUserLogin_UserGroup_Mapping>();
            this.ExternalUserTransations = new HashSet<ExternalUserTransation>();
            this.ExternalUserTransations1 = new HashSet<ExternalUserTransation>();
        }
    
        public int ExternalUserLoginID { get; set; }
        public Nullable<int> ExternalUserInfoID { get; set; }
        public string ExternalUserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public Nullable<System.DateTime> CurrentSuccesfulLogin { get; set; }
        public Nullable<System.DateTime> LastSuccesfulLogin { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUserAcademicInfo> ExternalUserAcademicInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUserAcademicInfo> ExternalUserAcademicInfoes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUserAcademicInfo> ExternalUserAcademicInfoes2 { get; set; }
        public virtual ExternalUserInfo ExternalUserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUserLogin_UserGroup_Mapping> ExternalUserLogin_UserGroup_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUserTransation> ExternalUserTransations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUserTransation> ExternalUserTransations1 { get; set; }
    }
}
