//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternalUser
    {
        public int InternalUserID { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> CurrentSuccesfulLogin { get; set; }
        public Nullable<System.DateTime> LastSuccesfulLogin { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
