//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolFeeStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SchoolFeeStructure()
        {
            this.StudentFeesDetails = new HashSet<StudentFeesDetail>();
        }
    
        public int SchoolFeeStructureId { get; set; }
        public System.Guid SchoolFeeStructureGuid { get; set; }
        public int SchoolID { get; set; }
        public int FeeTypeId { get; set; }
        public int FeeFrequencyId { get; set; }
        public Nullable<int> SchoolStandardID { get; set; }
        public decimal Amount { get; set; }
        public string Remark { get; set; }
        public int AcademicYearId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual FeeFrequency FeeFrequency { get; set; }
        public virtual FeeType FeeType { get; set; }
        public virtual School School { get; set; }
        public virtual SchoolStandard SchoolStandard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentFeesDetail> StudentFeesDetails { get; set; }
    }
}
