//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSEntities : DbContext
    {
        public SMSEntities()
            : base("name=SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AcademicYear> AcademicYears { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ExternalUserAcademicInfo> ExternalUserAcademicInfoes { get; set; }
        public virtual DbSet<ExternalUserInfo> ExternalUserInfoes { get; set; }
        public virtual DbSet<ExternalUserLogin> ExternalUserLogins { get; set; }
        public virtual DbSet<ExternalUserLogin_UserGroup_Mapping> ExternalUserLogin_UserGroup_Mapping { get; set; }
        public virtual DbSet<ExternalUserTransation> ExternalUserTransations { get; set; }
        public virtual DbSet<FeeFrequency> FeeFrequencies { get; set; }
        public virtual DbSet<FeeType> FeeTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<InternalUser> InternalUsers { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<SchoolFeeStructure> SchoolFeeStructures { get; set; }
        public virtual DbSet<SchoolSection> SchoolSections { get; set; }
        public virtual DbSet<SchoolStandard> SchoolStandards { get; set; }
        public virtual DbSet<SchoolStream> SchoolStreams { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Standard> Standards { get; set; }
        public virtual DbSet<Stream> Streams { get; set; }
        public virtual DbSet<StudentAcademicDetail> StudentAcademicDetails { get; set; }
        public virtual DbSet<StudentContact> StudentContacts { get; set; }
        public virtual DbSet<StudentFeesDetail> StudentFeesDetails { get; set; }
        public virtual DbSet<StudentHistory> StudentHistories { get; set; }
        public virtual DbSet<StudentInfo> StudentInfoes { get; set; }
        public virtual DbSet<StudentParentInfo> StudentParentInfoes { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
    }
}
