//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeesDetail
    {
        public int StudentFeesDetailId { get; set; }
        public System.Guid StudentFeesDetailGuid { get; set; }
        public int StudentId { get; set; }
        public int SchoolFeeStructureId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SchoolFeeStructure SchoolFeeStructure { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
