//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicDetail
    {
        public int StudentAcademicDetailsId { get; set; }
        public System.Guid StudentAcademicDetailsGuid { get; set; }
        public int StudentId { get; set; }
        public int SchoolStandardId { get; set; }
        public int SchoolSectionId { get; set; }
        public int AcademicYearId { get; set; }
        public Nullable<int> SchoolStreamID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual SchoolSection SchoolSection { get; set; }
        public virtual SchoolStandard SchoolStandard { get; set; }
        public virtual SchoolStream SchoolStream { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
