//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentContact
    {
        public int StudentContactId { get; set; }
        public System.Guid StudentContactGuid { get; set; }
        public int StudentId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Landmark { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public int Zip { get; set; }
        public string Contact1 { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
