//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentParentInfo
    {
        public int StudentParentId { get; set; }
        public System.Guid StudentParentGuid { get; set; }
        public int StudentId { get; set; }
        public string ParentType { get; set; }
        public string Parentname { get; set; }
        public string Qualification { get; set; }
        public string Occupation { get; set; }
        public Nullable<decimal> AnnualIncome { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
