//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentHistory
    {
        public int StudentHistoryId { get; set; }
        public System.Guid StudentHistoryGuid { get; set; }
        public int StudentId { get; set; }
        public string LastAttendedSchool { get; set; }
        public string LastClassCompleted { get; set; }
        public string LastAcedemicYear { get; set; }
        public string LastAttendedBoard { get; set; }
        public decimal LastClassResult { get; set; }
    
        public virtual StudentInfo StudentInfo { get; set; }
    }
}
