//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserGroup()
        {
            this.ExternalUserLogin_UserGroup_Mapping = new HashSet<ExternalUserLogin_UserGroup_Mapping>();
            this.InternalUsers = new HashSet<InternalUser>();
        }
    
        public int UserGroupId { get; set; }
        public string UserGroupName { get; set; }
        public bool IsInternal { get; set; }
        public bool IsExternal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalUserLogin_UserGroup_Mapping> ExternalUserLogin_UserGroup_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InternalUser> InternalUsers { get; set; }
    }
}
